# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'


steps:
- task: YarnInstaller@3
  inputs:
    versionSpec: '1.x'

- task: CmdLine@2
  inputs:
    script: |
      yarn install